### PR TITLE
Davey/prepopulate - see message below

### PR DESCRIPTION
**Pull request by dYedid**
Now compiling successfully --> fixed typescript errors; also rough switch/case conditionals for message-field types. (note: chrome console displays several errors upon webpage load)

### CODE REVIEW

**Comment by dYedid** [comment]
Completed: proto button; popup displaying proto file (need to pretty-print proto file)

Refactored- proto type is now 'string | ArrayBuffer', not object. 
Initial-state.proto = '' (not {}).

**Comment by dYedid** [comment]
Popup completed.

**Review by CedricTheofanous — DISMISSED** [review]
Looks great! Good work Davey.

**Review by tammytan95 — DISMISSED** [review]
tt - approved

**Pull request closed without merging**
